Description: This template creates Lambda layers for python libraries such as Numpy, pandas and pytesseract.

Resources:

  LambdaNumpyLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Description: LambdaFunction NumpyLayer
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.7
        - python3.8
      Content: ./src/lambda/layer/numpy/

  LambdaPandasLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Description: LambdaFunction Pandas Layer
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.7
        - python3.8
      Content: src/lambda/layer/pandas

  LambdaTesseractLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Description: LambdaFunction Tesseract Layer
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.8
      Content: src/lambda/layer/pytesseract

Outputs:

  LambdaNumpyLayerArn:
    Description: LambdaNumpyLayer Arn
    Value: !Ref LambdaNumpyLayer
    Export:
      Name: !Join ['-', [!Ref 'AWS::StackName', 'LambdaNumpyLayerArn']]

  LambdaPandasLayerArn:
    Description: LambdaPandasLayer Arn
    Value: !Ref LambdaPandasLayer
    Export:
      Name: !Join ['-', [!Ref 'AWS::StackName', 'LambdaPandasLayerArn']]

  LambdaTesseractLayerArn:
    Description: LambdaTesseractLayer Arn
    Value: !Ref LambdaTesseractLayer
    Export:
      Name: !Join ['-', [!Ref 'AWS::StackName', 'LambdaTesseractLayerArn']]